### ISSUE TITLE
iOS Safari radio inputs

### ISSUE THREAD

**Issue by mdmoreau** [csstools/sanitize.css#101]
All radio input styles are being removed in iOS Safari but not other browsers.  Is this intended behavior?  They were easy enough to add back in, but it seemed like the goal was to keep the default OS/browser radio styles intact - I've only seen this not be the case in iOS Safari.

**Comment by jonathantneal** [comment]
I am restoring many of the default stylings in the next release. I am very close to that release.

**Comment by mdmoreau** [comment]
Awesome, thanks!  Let me know if there's anything I can do to help.

**Comment by jonathantneal** [comment]
This should be resolved. Would you like to be sure it’s working on your end, @mdmoreau ?

**Comment by mdmoreau** [comment]
Still getting the same behavior unfortunately.  It looks like it has to do with these couple of lines: https://github.com/jonathantneal/sanitize.css/blob/master/sanitize.css#L343-L344.

Just did some quick testing, and it seems like using `input:not([type='radio']):not([type='checkbox'])` instead of `input` fixes the problem.  I haven't tried any of the other input types that vary between browsers, but my guess is there might be some others that shouldn't be targeted as well.

Is a change like this something you'd be interested in?  I'd be happy to find out if any other types should be excluded if you think it would be worth the time.

**Comment by mattpilott** [comment]
@mdmoreau that line makes it quite specific, it could be annoying to override input

**Comment by luminarious** [comment]
@mdmoreau That's an excellent way of doing it, as all other inputs except checkbox and radio make sense as some kind of field.

**Comment by sam-ghosh** [comment]
Hello all, I am seeing some very strange styling for radio and checkbox inputs in the IOS Safari upon using sanitize.css (which is used in React Boilerplate). Is this because of the issue above?


![screen shot 2016-12-26 at 03 08 28](https://cloud.githubusercontent.com/assets/5731118/21474542/d225a3ac-cb18-11e6-920b-65c3640c6fa4.png)

**Comment by mdmoreau** [comment]
Yeah that looks the same as how things did when I originally posted the issue.

**Comment by jonathantneal** [comment]
I’ll look into this again.

**Comment by jonathantneal** [comment]
I think I’ll get out of styling form controls. Leave it to another library.

**Comment by jonathantneal** [comment]
Left most of these form controls in v6.
